site_name: Guida VisiData
site_url: https://ondata.github.io/guidaVisiData/


repo_url: https://github.com/ondata/guidaVisiData
repo_name: guidaVisiData
edit_uri: edit/master/docs/

copyright: '<b>Guida VisiData</b> è un progetto dell''<a href="https://twitter.com/ondatait" target="_blank">associazione onData</a> | licenza <a href="https://creativecommons.org/licenses/by/4.0/deed.it" target="_blank">CC BY 4.0</a>'

theme:
  name: material
  highlightjs: true
  custom_dir: overrides
  favicon: imgs/favicon.ico
  palette:
    scheme: preference
  language: it
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
  font:
    text: Montserrat


nav:
    - Home: README.md
    - Guida:
      - Installazione: installazione.md
      - Primi passi: primiPassi.md
      - Navigare tra i dati: navigare.md
      - Lavorare sui dati:
        - sulle righe: lavorareRighe.md
        - sulle colonne: lavorareColonne.md
        - sulle celle: lavorareCelle.md
      - Fogli: fogli.md
      - Ricette: ricette.md
      - Formati: formati.md
      - Configurazione: configurazione.md
      - Contributi:
        - Cheat-sheet: cheatsheet.md
        - 10 modi di usarlo: dieciModi.md
    - Supporto: supportare.md
    - Aiuto: aiuto.md
    - Note: note.md

extra:
 social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ondatait
      name: account twitter

# foglio di stile personalizzato
extra_css:
  - stylesheets/style.css

plugins:
- search
- mkdocstrings

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

markdown_extensions:
- admonition
- attr_list
- footnotes
- meta
- mkdocs-click
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.critic:
      mode: view
- pymdownx.details
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
- pymdownx.tilde
- toc:
      permalink: true
      toc_depth: 3
