site_name: Guida VisiData
site_url: https://example.com/


repo_url: https://github.com/ondata/guidaVisiData
repo_name: guidaVisiData
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    scheme: preference
  language: it
  features:
    - navigation.top

nav:
    - Home: README.md
    - Installazione: installazione.md
    - Navigare tra i dati: navigare.md
    - Lavorare sui dati:
      - sulle righe: lavorareRighe.md
      - sulle colonne: lavorareColonne.md
      - sulle celle: lavorareCelle.md
    - Fogli: fogli.md
    - Ricette: ricette.md
    - Configurazione: configurazione.md
    - Cheat-sheet: cheatsheet.md
    - 10 modi di usarlo: dieciModi.md
    - Supportare VisiData: supportare.md
    - Aiuto: aiuto.md
    - Note: note.md

plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
- meta
